// export const actionType = {
//     REGISTER_USER: 'REGISTER_USER',
//     REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
//     REGISTRATION_ERROR: 'REGISTRATION_ERROR',
//     LOGIN_USER: 'LOGIN_USER',
//     LOGIN_SUCCESS: 'LOGIN_SUCCESS',
//     LOGIN_ERROR: 'LOGIN_ERROR',
//     CLOSE_ERROR: 'CLOSE_ERROR',
//     CLOSE_SUCCESS: 'CLOSE_SUCCESS',
//     TRIP_DETAIL_ONE: 'TRIP_DETAIL_ONE',
//     TRIP_DETAIL_TWO: 'TRIP_DETAIL_TWO',
//   };
  